### ISSUE TITLE
Dataset access request

### ISSUE THREAD

**Issue by asigalov61** [GigaMidiDataset/The-GigaMIDI-dataset-with-loops-and-expressive-music-performance-detection#1]
@GigaMidiDataset Hello!

Please approve my Hugging Face request for dataset access. Its been pending for a while.

Thank you.

**Comment by erl-j** [comment]
Same here

**Comment by GigaMidiDataset** [comment]
Apologies for not responding sooner. The GigaMIDI dataset is connected to our academic paper, which is still under review, but we plan to release it properly very soon, as you can see it's anonymized at the moment due to the double blind review process. Thank you for your patience.
